SELECT CONCAT ('google', '.com') AS ConcatFunction

SELECT ASCII (ProductID) NumberCodeOfID
FROM Products

SELECT ASCII ('0')

SELECT CHAR (64) AS CodeToCharacter

SELECT LOWER ('SQL FUNCTIONS')

SELECT UPPER ('SQL FUNCTIONS')

SELECT REPLACE ('TUTORIAL', 'T', 't')

SELECT GETDATE()

SELECT DAY ('2022/12/09') AS DAY

SELECT MONTH ('2022/12/09') AS MONTH

SELECT YEAR ('2022/12/09') AS YEAR